from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal
from typing import Any


@dataclass
class CustomerInfo:
    """Customer billing information for a payment request.

    Attributes:
        name: Full name of the customer.
        email: Email address of the customer.
        address1: Primary billing address line.
        city: Billing city.
        postcode: Billing postal code.
        country: Billing country.
        phone: Customer phone number.
        address2: Optional secondary address line.
    """

    name: str
    email: str
    address1: str
    city: str
    postcode: str
    country: str
    phone: str
    address2: str = ""


@dataclass
class ShippingInfo:
    """Shipping destination information for a payment request.

    Attributes:
        ship_name: Name of the shipping recipient.
        address: Shipping address line.
        city: Shipping city.
        postcode: Shipping postal code.
        country: Shipping country.
    """

    ship_name: str
    address: str
    city: str
    postcode: str
    country: str


@dataclass
class PaymentRequest:
    """All data required to initiate an SSLCommerz payment session.

    Required fields must be supplied at construction. Optional fields
    default to empty strings or sensible defaults.

    Raises:
        ValueError: If store_id or store_pass are empty, or total_amount <= 0.

    Attributes:
        store_id: SSLCommerz store ID credential.
        store_pass: SSLCommerz store password credential.
        total_amount: Transaction amount as a Decimal.
        currency: ISO 4217 currency code (e.g. "BDT", "USD").
        tran_id: Unique transaction ID generated by the caller.
        success_url: URL SSLCommerz redirects to on payment success.
        fail_url: URL SSLCommerz redirects to on payment failure.
        cancel_url: URL SSLCommerz redirects to on cancellation.
        ipn_url: URL for Instant Payment Notification webhook.
        product_name: Name of the product being purchased.
        product_category: Category of the product.
        product_profile: SSLCommerz product profile identifier.
        num_of_item: Number of items in the order.
        shipping_method: Shipping method indicator ("YES" / "NO").
        customer: Optional customer billing details.
        shipping: Optional shipping destination details.
        value_a: Optional custom pass-through value A.
        value_b: Optional custom pass-through value B.
        value_c: Optional custom pass-through value C.
        value_d: Optional custom pass-through value D.
    """

    store_id: str
    store_pass: str
    total_amount: Decimal
    currency: str
    tran_id: str
    success_url: str
    fail_url: str
    cancel_url: str
    ipn_url: str = ""
    product_name: str = ""
    product_category: str = ""
    product_profile: str = "None"
    num_of_item: int = 1
    shipping_method: str = "NO"
    customer: CustomerInfo | None = None
    shipping: ShippingInfo | None = None
    value_a: str = ""
    value_b: str = ""
    value_c: str = ""
    value_d: str = ""

    def __post_init__(self) -> None:
        """Validate required fields after dataclass initialization."""
        if not self.store_id:
            raise ValueError("store_id is required")
        if not self.store_pass:
            raise ValueError("store_pass is required")
        if self.total_amount <= 0:
            raise ValueError(f"total_amount must be positive, got {self.total_amount}")


@dataclass(frozen=True)
class PaymentResponse:
    """Result of a successful payment session initiation.

    Attributes:
        status: Raw status string from SSLCommerz (e.g. "SUCCESS").
        session_key: SSLCommerz session key for the initiated payment.
        gateway_url: URL to redirect the user to complete payment.
        failed_reason: Failure reason if status is not SUCCESS.
        is_success: True when status == "SUCCESS".
    """

    status: str
    session_key: str = ""
    gateway_url: str = ""
    failed_reason: str = ""

    @property
    def is_success(self) -> bool:
        """Return True if the payment session was successfully created."""
        return self.status == "SUCCESS"


@dataclass(frozen=True)
class ValidationResponse:
    """Result of a transaction validation request.

    Attributes:
        status: Validation status string from SSLCommerz (e.g. "VALIDATED").
        data: Full raw response dict from SSLCommerz for callers needing extra fields.
        is_validated: True when status == "VALIDATED".
    """

    status: str
    data: dict[str, Any]

    @property
    def is_validated(self) -> bool:
        """Return True if the transaction was successfully validated."""
        return self.status == "VALIDATED"
