name: Test SSLCommerz Python API

on:
  push:
    branches: [ dev ]

jobs:
  build:
    name: Test SSLCommerz Python API
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Requirements
      run: >-
        python -m
        pip install
        -r
        requirements.txt
    - name: Install Pytest
      run: >-
        python -m
        pip install
        pytest
    - name: Run Test
      run: >-
        pytest
        -vv

